# ----------------------------------------------------------------------------
# Copyright (c) 2020, Diego Garcia Huerta.
#
# Your use of this software as distributed in this GitHub repository, is
# governed by the Apache License 2.0
#
# Your use of the Shotgun Pipeline Toolkit is governed by the applicable
# license agreement between you and Autodesk / Shotgun.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------


# Author: Diego Garcia Huerta
# Contact: https://www.linkedin.com/in/diegogh/
#
# YOU SHOULD MERGE these entries into your template.yml configuration file, as
# THIS FILE BY ITSELF WILL NOT WORK
# These are the additions to the template.yml to get the engine up and
# running with the default tk-apps


paths:

    #
    # Blender
    #

    # Asset based paths

    # Location of a work area
    asset_work_area_blender:
        definition: '@asset_root/work/blender'
        root_name: 'primary'

    # Location of a publish area
    asset_publish_area_blender:
        definition: '@asset_root/publish/blender'
        root_name: 'primary'

    # Location of WIP session files
    blender_asset_work:
        definition: '@asset_work_area_blender/{name}.v{version}.blend'
        root_name: 'primary'

    # Location of backups of WIP session files
    blender_asset_snapshot:
        definition: '@asset_work_area_blender/snapshots/{name}.v{version}.{timestamp}.blend'
        root_name: 'primary'

    # Location of the published session files
    blender_asset_publish:
        definition: '@asset_publish_area_blender/{name}.v{version}.blend'
        root_name: 'primary'

    # Shot based paths

    # define the location of a work area
    shot_work_area_blender:
        definition: '@shot_root/work/blender'
        root_name: 'primary'

    # define the location of a publish area
    shot_publish_area_blender:
        definition: '@shot_root/publish/blender'
        root_name: 'primary'

    # The location of WIP session files
    blender_shot_work:
        definition: '@shot_root/work/blender/{name}.v{version}/{name}.v{version}.blend'
        root_name: 'primary'

    # The location of backups of WIP session files
    blender_shot_snapshot:
        definition: '@shot_root/work/blender/snapshots/{name}.v{version}/{name}.v{version}.{timestamp}.blend'
        root_name: 'primary'

    # The location of published session files
    blender_shot_publish:
        definition: '@shot_root/publish/blender/{name}.v{version}/{name}.v{version}.blend'
        root_name: 'primary'
